### ISSUE TITLE
Type (1/x or type (1÷ will crash the app

### ISSUE THREAD

**Issue by chaowangCanada** [transcendental-team/transcend-calculations#11]
Type (1/x or type (1÷ will crash the app

Tested on Calculator_release 1.0

**Comment by tshaynik** [comment]
Can you check your code? Testing the parser alone, I get:
For 1/     :
Invalid syntax! You may be missing an operand.
For 1+    : 
Invalid syntax! You may be missing an operand.

**Comment by chaowangCanada** [comment]
Correction : 1/) cause the crash. 

need to add a check in the applyOperation(), if first operand or second operand is empty

**Comment by chaowangCanada** [comment]
Fixed in release1.1
