### ISSUE TITLE
“3abs(3)” “3abs()” give wrong result

### ISSUE THREAD

**Issue by chaowangCanada** [transcendental-team/transcend-calculations#22]
“3abs(3)” should work as same as 3sin(3). Currently work as error message “invalid expression”

“3abs()” should work as same as 3sin(). “invalid syntax". Currently work as "3abs() = 3"

It should be a quick fix. Dan. Could you solve this today. Before the deliverable 3 deadline?

**Comment by tshaynik** [comment]
It's resolved.
