### ISSUE TITLE
Function 10^x requires more accuracy for large value of x

### ISSUE THREAD

**Issue by chaowangCanada** [transcendental-team/transcend-calculations#3]
Use current pow10() method to perform: 10^10.
- Result is 9.999999999E9. This is clearly not an accurate result. 

when pow10() input parameter being an integer. The result  should be 100% accuracy in all integer digit.

-Logged by Chao Wang.
26/02/2016

**Comment by xdwang0726** [comment]
I think the reason is that I called Dan's ln10 function. Since if I use Math.log(10.0) instead of Dan's function, I can definitely get the accurate result.

**Comment by tshaynik** [comment]
The above shouldn't make any difference:
Math.log(10):  2.3025850929940455
Functions.ln(10):   2.302585092994046
I fixed the issue in the implementation of the pow10 function that was causing the problem. It is now accurate to the 12th decimal place (more than shows up in the calculator).
