### ISSUE TITLE
Number before a function doesn't multiply

### ISSUE THREAD

**Issue by Blynks** [transcendental-team/transcend-calculations#9]
If a user enters a number before any of our functions then it will not recognize 
automatically as multiplication. This results in an error.

ex. 5log5 => error
It should evaluate 5*log(5)

**Comment by chaowangCanada** [comment]
https://goo.gl/photos/BqXnAL7nKN5cpXW46

**Comment by chaowangCanada** [comment]
[https://goo.gl/photos/BqXnAL7nKN5cpXW46](url)

**Comment by chaowangCanada** [comment]
[https://goo.gl/photos/BqXnAL7nKN5cpXW46](url)

**Comment by chaowangCanada** [comment]
![image](https://cloud.githubusercontent.com/assets/15674468/13931612/5d8d10fe-ef61-11e5-96f9-6a94472a314a.png)

**Comment by tshaynik** [comment]
This issue has been fixed in the GUI release 2 branch
